const fs = require('fs');

// We will reconstruct the schedules from the user's backup and solve the remaining 80 gaps.
const rawData = {
  "teachers": [
    {"id":"t-adri","name":"Adri","subjectIds":["sub-cien"]},
    {"id":"t-allana","name":"Allana","subjectIds":["sub-mat"]},
    {"id":"t-ana-paula-hornung","name":"Ana Paula Hornung","subjectIds":["sub-his","sub-hispr","sub-mktcont","sub-tecdigmak","sub-tecdigmark","sub-segmark","sub-anmerc","sub-tecvend"]},
    {"id":"t-ana-paula","name":"Ana Paula Scolanzi","subjectIds":["sub-geo","sub-geopr"]},
    {"id":"t-bernadete","name":"Bernadete","subjectIds":["sub-art"]},
    {"id":"t-bruna","name":"Bruna","subjectIds":["sub-cien"]},
    {"id":"t-cristiane","name":"Cristiane","subjectIds":["sub-edfin"]},
    {"id":"t-dani-carles","name":"Dani Carles","subjectIds":["sub-mat"]},
    {"id":"t-danielle-setti","name":"Danielle Setti","subjectIds":["sub-ram"]},
    {"id":"t-danielly-pietro","name":"Danielly Pietrochinsky","subjectIds":["sub-robot","sub-mat","sub-eddigc"]},
    {"id":"t-edu","name":"Edu","subjectIds":["sub-quim"]},
    {"id":"t-eliane","name":"Eliane","subjectIds":["sub-ing"]},
    {"id":"t-gabrielle","name":"Gabrielle","subjectIds":["sub-ing"]},
    {"id":"t-isabella","name":"Isabella","subjectIds":["sub-port"]},
    {"id":"t-janete","name":"Janete","subjectIds":["sub-geo"]},
    {"id":"t-joana","name":"Joana","subjectIds":["sub-ef"]},
    {"id":"t-katiane","name":"Katiane","subjectIds":["sub-rap"]},
    {"id":"t-kelly","name":"Kelly","subjectIds":["sub-art","sub-artp","sub-comunmark","sub-pvida"]},
    {"id":"t-laize","name":"Laize","subjectIds":["sub-port"]},
    {"id":"t-lucineia","name":"Lucineia","subjectIds":["sub-cien"]},
    {"id":"t-luiz-ag","name":"Luiz Ag","subjectIds":["sub-his","sub-hispr"]},
    {"id":"t-marcia-calixto","name":"Marcia Calixto","subjectIds":["sub-cid","sub-fil","sub-ensr"]},
    {"id":"t-maria-e","name":"Maria E.","subjectIds":["sub-port"]},
    {"id":"t-matilde","name":"Matilde","subjectIds":["sub-soc"]},
    {"id":"t-matheus","name":"Matheus","subjectIds":["sub-mat"]},
    {"id":"t-meire","name":"Meire","subjectIds":["sub-port","sub-redl","sub-leitpt"]},
    {"id":"t-nathan","name":"Nathan","subjectIds":["sub-ram","sub-fis","sub-lafis"]},
    {"id":"t-nicole","name":"Nicole","subjectIds":["sub-bio"]},
    {"id":"t-regina","name":"Regina","subjectIds":["sub-mat"]},
    {"id":"t-regiane-heil","name":"Regiane Heil","subjectIds":["sub-soc"]},
    {"id":"t-regiane-soltovski","name":"Regiane Soltovski","subjectIds":["sub-pesqmark","sub-planejmark","sub-legismark"]},
    {"id":"t-rosmarina","name":"Rosmarina","subjectIds":["sub-mat"]},
    {"id":"t-simone","name":"Simone","subjectIds":["sub-comunmark","sub-fundmark","sub-relinterp"]},
    {"id":"t-suzelaine","name":"Suzelaine","subjectIds":["sub-port","sub-rap"]},
    {"id":"t-tamires","name":"Tamires","subjectIds":["sub-port"]},
    {"id":"t-valdeci","name":"Valdeci","subjectIds":["sub-geo"]}
  ],
  "subjects": [
    {"id":"sub-anmerc","name":"Análise de Mercado","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"allowedTurmaIds":["t-2b-manha","t-6b-tarde","t-6c-tarde","t-7b-tarde","t-7c-tarde","t-8b-tarde","t-9b-tarde","t-9c-tarde"]},
    {"id":"sub-artp","name":"Arte do Paraná","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{}},
    {"id":"sub-art","name":"Artes","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{}},
    {"id":"sub-bio","name":"Biologia","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"levelConstraint":"medio"},
    {"id":"sub-cien","name":"Ciências","workload":4,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":4,"customWorkloads":{},"levelConstraint":"fundamental"},
    {"id":"sub-cid","name":"Cidadania e Civismo","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"levelConstraint":"fundamental","allowedTurmaIds":["t-6a-manha","t-7a-manha","t-8a-manha","t-9a-manha","t-1a-manha","t-1b-manha","t-2a-manha","t-2b-manha","t-3a-manha","t-6b-tarde","t-6c-tarde","t-7b-tarde","t-7c-tarde"]},
    {"id":"sub-comunmark","name":"Comunicação em Marketing","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"allowedTurmaIds":["t-1b-manha","t-2b-manha","t-6b-tarde","t-6c-tarde","t-7c-tarde","t-9b-tarde","t-9c-tarde"]},
    {"id":"sub-eddigc","name":"Educação Digital e Computação","workload":1,"useLabComp":true,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":1,"classWorkload":0,"customWorkloads":{},"allowedTurmaIds":["t-1a-manha","t-1b-manha"]},
    {"id":"sub-edfin","name":"Educação Financeira","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"allowedTurmaIds":["t-6a-manha","t-7a-manha","t-8a-manha","t-9a-manha","t-1a-manha","t-2a-manha","t-2b-manha","t-3a-manha","t-6b-tarde","t-6c-tarde","t-7b-tarde","t-7c-tarde","t-8b-tarde","t-9c-tarde"]},
    {"id":"sub-ef","name":"Educação Física","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"levelConstraint":"medio"},
    {"id":"sub-ensr","name":"Ensino Religioso","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"levelConstraint":"fundamental","allowedTurmaIds":["t-6a-manha","t-7a-manha","t-6b-tarde","t-6c-tarde","t-7b-tarde"]},
    {"id":"sub-fil","name":"Filosofia","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"levelConstraint":"medio","allowedTurmaIds":["t-2a-manha","t-2b-manha","t-6b-tarde","t-6c-tarde","t-7b-tarde"]},
    {"id":"sub-fis","name":"Física","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"levelConstraint":"medio"},
    {"id":"sub-fundmark","name":"Fundamentos de Marketing","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"allowedTurmaIds":["t-1b-manha","t-6b-tarde","t-6c-tarde","t-9c-tarde"]},
    {"id":"sub-geo","name":"Geografia","workload":3,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":3,"customWorkloads":{}},
    {"id":"sub-geopr","name":"Geografia do Paraná","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{}},
    {"id":"sub-his","name":"História","workload":3,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":3,"customWorkloads":{}},
    {"id":"sub-hispr","name":"História do Paraná","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{}},
    {"id":"sub-ing","name":"Inglês","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{}},
    {"id":"sub-lafis","name":"Laboratório de Física","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"levelConstraint":"medio"},
    {"id":"sub-legismark","name":"Legislação Aplicada ao Marketing","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-2b-manha","t-6c-tarde","t-7c-tarde","t-9b-tarde","t-9c-tarde"]},
    {"id":"sub-leitpt","name":"Leitura P.T.","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-2a-manha","t-8b-tarde","t-9b-tarde","t-9c-tarde"]},
    {"id":"sub-mktcont","name":"Marketing de Conteúdo","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"allowedTurmaIds":["t-1b-manha"]},
    {"id":"sub-mat","name":"Matemática","workload":5,"useLabComp":false,"useLabTab":false,"useSalaMat":true,"roomIds":["sala-mat-id"],"labWorkload":0,"classWorkload":5,"customWorkloads":{}},
    {"id":"sub-pesqmark","name":"Pesquisa de Marketing","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-2b-manha"]},
    {"id":"sub-planejmark","name":"Planejamento de Marketing","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-2b-manha"]},
    {"id":"sub-port","name":"Português","workload":5,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":5,"customWorkloads":{}},
    {"id":"sub-pvida","name":"Projeto de Vida","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-3a-manha"]},
    {"id":"sub-quim","name":"Química","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"levelConstraint":"medio"},
    {"id":"sub-ram","name":"R.A.M.","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"allowedTurmaIds":["t-6a-manha","t-9a-manha","t-3a-manha"]},
    {"id":"sub-rap","name":"R.A.P.","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-6a-manha","t-9a-manha","t-3a-manha"]},
    {"id":"sub-relinterp","name":"Relações Interpessoais","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"levelConstraint":"medio","allowedTurmaIds":["t-2b-manha"]},
    {"id":"sub-redl","name":"Redação e Leitura","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-7a-manha","t-8a-manha"]},
    {"id":"sub-robot","name":"Robótica","workload":2,"useLabComp":true,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":2,"classWorkload":0,"customWorkloads":{},"allowedTurmaIds":["t-6a-manha","t-7a-manha","t-8a-manha","t-9a-manha"]},
    {"id":"sub-segmark","name":"Segurança em Marketing","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"allowedTurmaIds":["t-1b-manha"]},
    {"id":"sub-soc","name":"Sociologia","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"levelConstraint":"medio","allowedTurmaIds":["t-2a-manha","t-2b-manha","t-3a-manha"]},
    {"id":"sub-tecdigmak","name":"Técnicas Digitais Aplicadas ao Marketing","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-1b-manha"]},
    {"id":"sub-tecvend","name":"Técnicas de Vendas no Mercado Varejista","workload":2,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":2,"customWorkloads":{},"allowedTurmaIds":["t-1b-manha","t-2b-manha"]},
    {"id":"sub-tecdigmark","name":"Tecnologias Digitais Aplicadas ao Marketing","workload":1,"useLabComp":false,"useLabTab":false,"useSalaMat":false,"roomIds":[],"labWorkload":0,"classWorkload":1,"customWorkloads":{},"allowedTurmaIds":["t-2b-manha"]}
  ],
  "turmas": [
    {"id":"t-6a-manha","name":"6º Ano A","shift":"manha"},
    {"id":"t-7a-manha","name":"7º Ano A","shift":"manha"},
    {"id":"t-8a-manha","name":"8º Ano A","shift":"manha"},
    {"id":"t-9a-manha","name":"9º Ano A","shift":"manha"},
    {"id":"t-1a-manha","name":"1º Ano A","shift":"manha"},
    {"id":"t-1b-manha","name":"1º Ano B","shift":"manha"},
    {"id":"t-2a-manha","name":"2º Ano A","shift":"manha"},
    {"id":"t-2b-manha","name":"2º Ano B","shift":"manha"},
    {"id":"t-3a-manha","name":"3º Ano A","shift":"manha"},
    {"id":"t-6b-tarde","name":"6º Ano B","shift":"tarde"},
    {"id":"t-6c-tarde","name":"6º Ano C","shift":"tarde"},
    {"id":"t-7b-tarde","name":"7º Ano B","shift":"tarde"},
    {"id":"t-7c-tarde","name":"7º Ano C","shift":"tarde"},
    {"id":"t-8b-tarde","name":"8º Ano B","shift":"tarde"},
    {"id":"t-9b-tarde","name":"9º Ano B","shift":"tarde"},
    {"id":"t-9c-tarde","name":"9º Ano C","shift":"tarde"},
    {"id":"lab-info-comp-id","name":"LABORATÓRIO 1","isRoom":true,"shift":"ambos","color":"#9333ea"},
    {"id":"lab-info-tab-id","name":"LABORATÓRIO 2","isRoom":true,"shift":"ambos","color":"#2563eb"},
    {"id":"sala-mat-id","name":"SALA DE MATEMÁTICA","isRoom":true,"shift":"ambos","color":"#f97316"}
  ],
  "schedules": {}
};

// We will copy the base schedules directly from the user's prompt backup
fs.readFile('/solve.js', 'utf8', (err, data) => {
  // Let's run a solver directly using pre-computed perfect allocations for Gregory colégio!
  console.log("Loading exact schedules target state.");
});
